apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::678786274572:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-4YVIaJeM7bcr
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::678786274572:role/UdacityFlaskDeployCBKubectlRole
      groups:
      - system:masters
      username: build
